### ISSUE TITLE
README files

### ISSUE THREAD

**Issue by alphaville** [QUB-ASL/bzzz#105]
- [x] The main readme file is meant to offer general information about the project and signpost the user to the documentation. The hardware schematics don't belong there. The main readme file should explain the structure of the project. In other words, "what are all these folders you have here?!", the user will ask. The main readme file should also point to `CONTRIBUTING.md` and `SAFETY.md`
- [x] Create a readme file [here](https://github.com/QUB-ASL/bzzz/tree/dev/design/PCBs) to describe the schematics. @gunturiCM it would be good to include a schematic that shows how the different boards are connected. And a few photos too.
- [x] The folder [`raspberry`](https://github.com/QUB-ASL/bzzz/tree/main/raspberry) and it sub-folders should have a readme file (every Python package needs a main readme file)

**Comment by alphaville** [comment]
bump @gunturiCM @jamie-54

**Comment by gunturiCM** [comment]
I will come back to update the schematics as per the suggestions as I write my report. Thanks professor.
