### ISSUE TITLE
Refuse to fly unless the switches are at the correct positions

### ISSUE THREAD

**Issue by alphaville** [QUB-ASL/bzzz#110]
Additional safety measure: The quadcopter should refuse to fly when the script starts unless the switches are at the correct positions (A: up, B: up, C: first position, D: down) **and** the throttle stick is fully down. In fact the buzzer should make a sound. Since we can control the buzzer only from the ESP, it should be good to implement this on the ESP.

**Comment by alphaville** [comment]
@gunturiCM will you take care of this?

**Comment by alphaville** [comment]
@jamie-54 @Yuanbwcx @Runway27 @pdavid747 @Minanchi We should take care of this issue before we start flying again to avoid accidents! Who can take care of this?

**Comment by alphaville** [comment]
@jamie-54 @Yuanbwcx @Runway27 @pdavid747 @Minanchi folks, I still haven't received any replies from you on this. Who can take care of this issue?

**Comment by jamie-54** [comment]
me and @Runway27 can look at this tomorrow

**Comment by alphaville** [comment]
@jamie-54 and @Runway27 - should we close this issue?

**Comment by Runway27** [comment]
Yes sir, this issue has been resolved. But the PR regarding this has issue #165 which is to be resolved.

**Comment by alphaville** [comment]
Indeed, PR #172 is addressing two issues (#110 and #165), but this is not good practice. A PR should aim to close one issue (even when it partly addresses multiple ones). In any case, #172 still has unresolved conversations and has not been approved. 

I suggest we make PR #172 address only #110, we then review it quickly, we merge it, and we open a PR to work on #165. Does this work, @Runway27 and @jamie-54?

**Comment by Runway27** [comment]
Yes sir, we can do that.

**Comment by jamie-54** [comment]
> Indeed, PR #172 is addressing two issues (#110 and #165), but this is not good practice. A PR should aim to close one issue (even when it partly addresses multiple ones). In any case, #172 still has unresolved conversations and has not been approved.
> 
> I suggest we make PR #172 address only #110, we then review it quickly, we merge it, and we open a PR to work on #165. Does this work, @Runway27 and @jamie-54?

Sounds good

**Comment by Runway27** [comment]
Are we happy to close this issue?

**Comment by jamie-54** [comment]
> Are we happy to close this issue?
Yea sounds good to me
