### ISSUE TITLE
Updated PCB's 

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#135]
## ESP Board
- [x] fix ESP pin layout 
Consider new IMUs 

## Pi Board 
- [x] Add buzzer
- [x] Add slot for HDMI
- [x] Add Anemometer header

## Sensor Board 
- [x] fix (swap) VL53L0X time of flight sensor SDA and SCL port
- [x] Add TeraBee time of flight sensor

**Comment by alphaville** [comment]
@jamie-54 are there any other updates we need? Is #136 ready for review?
