### ISSUE TITLE
Logo Makeover

### ISSUE THREAD

**Issue by ethetic** [QUB-ASL/bzzz#151]
### Describe the issue

The current logo has clipping and is pixelated when zoomed close. 
How about this SVG where it is cleaned up?

![BZZZ (1)](https://github.com/QUB-ASL/bzzz/assets/119050148/6db41c9b-13bb-41ad-bc09-76c0b879a295)

### Affected File

README.md

### Affected Line

--

**Comment by alphaville** [comment]
Thank you, @ethetic. This looks a lot better. Could we get rid of the pacifier?

**Comment by jamie-54** [comment]
Thanks @ethetic, it looks better than are current version. I'm happy to update it, what's your thoughts @alphaville?
