### ISSUE TITLE
Suspected typo 

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#152]
### Describe the issue

Think there is a typo, or we should change the variables name, you'll see.

### Affected File

raspberry/bzzz/main.py

### Affected Line

194 and 199

**Comment by alphaville** [comment]
What is the typo? Can you paste the code here?

**Comment by jamie-54** [comment]
![image](https://github.com/QUB-ASL/bzzz/assets/95449123/c4856739-ad97-4d17-8d9e-4322f8f881d0)

throttle in line 189 as well

**Comment by jamie-54** [comment]
can do
