### ISSUE TITLE
Kill motors when receiver gets disconnected

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#165]
### Describe the bug

We need to make sure that the motors are killed in case the receiver seems to be disconnected for more than a few milliseconds. We had tested it a few weeks ago, and the motors kept spinning after unplugging the receiver. 

### To Reproduce

Remove the receiver wires

### Minimum reproducible example

Guys, we should simplify bug reporting!

**Comment by alphaville** [comment]
We should update `SAFETY.md` with a list of all such safety measures that have been implemented on the quadcopter. We should also be testing that they work after every code update.

**Comment by alphaville** [comment]
Regarding simplifying the bug reporting, I'd vote in favour of getting rid of *all* fields. Have a look at [this repo](https://github.com/alphaville/optimization-engine/issues/new/choose) for example. 

@jamie-54 @Runway27 Any progress on this issue? I'll be available tomorrow afternoon if you like to chat.
