### ISSUE TITLE
Bash script to run Python script

### ISSUE THREAD

**Issue by alphaville** [QUB-ASL/bzzz#18]
Create a bash script that will: (i) activate the virtual environment, (ii) run the Python scirpt that reads from the RC and sends reference data to the ESP32. Make sure that the script is executed at startup.

**Comment by alphaville** [comment]
Completed

**Comment by alphaville** [comment]
@jamie-54 we should probably include some documentation somewhere (e.g., a README file in `hardware/docs`) on how to set up the cron job.

**Comment by alphaville** [comment]
I'm re-opening this issue. @gunturiCM can you take care of this?

**Comment by alphaville** [comment]
@jamie-54 we have a script on RPi. Can you put it here and make a PR?

**Comment by alphaville** [comment]
@jamie-54 any progress on this?

**Comment by jamie-54** [comment]
looking into it now
