### ISSUE TITLE
Initiate threading from main.py

### ISSUE THREAD

**Issue by Runway27** [QUB-ASL/bzzz#196]
### Describe the solution you'd like

We need to initiate threading for the barometer from the main file.

**Comment by alphaville** [comment]
@Runway27 Can you take care of this issue? It should be rather straightforward (just import the barometer class and use it)

**Comment by Runway27** [comment]
Yes sir. I have already created a branch. And have started working on it. Hopefully it will be completed on Monday.

**Comment by Runway27** [comment]
I’m planning to include both barometer and time of flight for the time being. And we can include GPS later.

**Comment by alphaville** [comment]
It should be really straightforward. Have a look at [multiple with statements](https://stackoverflow.com/questions/893333/multiple-variables-in-a-with-statement).

**Comment by Runway27** [comment]
Yes sir.

**Comment by jamie-54** [comment]
> I’m planning to include both barometer and time of flight for the time being. And we can include GPS later.

Include the anemometer as well please, [this](https://github.com/QUB-ASL/bzzz/blob/feature/186-save_wind_data_when_flying/raspberry/main.py) should help

**Comment by jamie-54** [comment]
Done
