### ISSUE TITLE
Mount GNSS and Antenna to bzzz

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#200]
### Describe the solution you'd like

* [x] Mount GNSS Module to lid
* [x] Redesign anemometer case or design a platform to mount the antenna to the carbon fibre tube
* [x] Mount Telemetry radio

I've ordered the [USB cable](https://www.amazon.co.uk/charge-Cable-MYLB-Braided-Charging-Black/dp/B07VCHVH9K?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&smid=ABZK44ZAKI0T3&th=1) to connect the GNSS Module to the Pi

**Comment by jamie-54** [comment]
I'm going to order [this connector](https://uk.rs-online.com/web/p/coaxial-connectors/4466432), to make it easier to mount the antenna

**Comment by jamie-54** [comment]
I was thinking something like this for anemometer case with antenna stand?
What's your thoughts?
![image](https://github.com/QUB-ASL/bzzz/assets/95449123/e37edca3-67d3-4885-b2e4-1062aa86cf08)

**Comment by jamie-54** [comment]
or maybe like this?

![image](https://github.com/QUB-ASL/bzzz/assets/95449123/35b2e389-5f37-4ed6-9698-7e0607940a30)

**Comment by alphaville** [comment]
@jamie-54 will there be some holes through the top plate? How will the antenna be supported?

**Comment by jamie-54** [comment]
> @jamie-54 will there be some holes through the top plate? How will the antenna be supported?

Hi, I haven't include holes as they where going to line up along the split in the case and it couldn't really be rotated because of the slot for the cable. I was thinking the double sided tape would be enough to hold it as the antenna is very lightweight?
I have this one printed and on the quadcopter and it looks like it will work well
