### ISSUE TITLE
ESCs not arming/functioning properly

### ISSUE THREAD

**Issue by alphaville** [QUB-ASL/bzzz#28]
The ESCs sometimes don't arm or don't function properly and then we have to reset the ESP32.

**Comment by alphaville** [comment]
[This guy here](https://youtu.be/ce81bDdOn0M) is suggesting to arm by increasing the throttle *gradually* from a low value to a higher one until the motors start to spin.

**Comment by alphaville** [comment]
More interestingly, [this guy](https://youtu.be/obR5Gky3sms) says that some ESCs may refuse to arm - or will behave weird - if they are powered, but it takes a long time to arm. In our `setup` function, `setupMotors` is called last. Maybe it should be first (after we beep the buzzer a couple of times to warn the operator).

**Comment by jamie-54** [comment]
Hi, we could check if the first video works.
Just checking I thought we didn't want to arm the motors until the Arm switch was used?
In which case we have to wait more than 20s for the Pi script to work.
The second video seems to imply that we shouldn't have an arm switch, it should just arm when the quadrotor is switched on. 
We could do this and just work with one on-off switch?

**Comment by alphaville** [comment]
Oh, yes, you're right. Moreover, the operator may simply want to arm the ESCs after some time. Did you try the first solution?

**Comment by alphaville** [comment]
@jamie-54 if the problem hasn't been resolved we should ask a question at one of the following channels:

- [Electronics SE](https://electronics.stackexchange.com/)
- [r/Multicopter/](https://www.reddit.com/r/Multicopter/) on Reddit
- [RC_ESC on GitHub](https://github.com/RB-ENantel/RC_ESC?utm_source=platformio&utm_medium=piohome)

**Comment by alphaville** [comment]
That's excellent - we're narrowing it down...

**Comment by gunturiCM** [comment]
This has been fixed and addressed in #52 .

**Comment by alphaville** [comment]
Reopening because the PR has not been reviewed/merged

**Comment by gunturiCM** [comment]
This has been fixed and addressed in #52 and the fix has been approved now.
