### ISSUE TITLE
Tidy up main.cpp 

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#41]
Remove functions from the top (above `setup`) of  `main.cpp` and put them in their correct files.

**Comment by jamie-54** [comment]
Should the likes of `setupMotors` be in the `motors.cpp`?
What's your thoughts @alphaville @gunturiCM ?

**Comment by alphaville** [comment]
@jamie-54 sounds reasonable. Also `buzz` could go into a file with utility functions. Should this be `config`?

**Comment by alphaville** [comment]
@jamie-54 have a look at #45

**Comment by jamie-54** [comment]
> @jamie-54 have a look at #45

will do thanks

**Comment by jamie-54** [comment]
Issue resolved
