### ISSUE TITLE
Delete Branches

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#49]
Hi, I see we have a view branches that seem to be out of date or not used anymore. 
Should we delete them to keep the repo tidy?

**Comment by alphaville** [comment]
Of course. I deleted a few. We now have only `main`, `dev`, and `feature/arm-kill`, which hasn't been merged and seems to be a little old.

**Comment by jamie-54** [comment]
I think `feature/arm-kill` can be deleted as well since we have the arm and kill switches working
