### ISSUE TITLE
Throttle capping 

### ISSUE THREAD

**Issue by jamie-54** [QUB-ASL/bzzz#55]
Just a quick point, we cap the throttle in the code and on the remote. 
Do we need both?
It works with both but just thought I'd make us all aware this is what we are doing.

**Comment by gunturiCM** [comment]
I think it is a good idea to cap it in the code regardless of the setting on the remote.

**Comment by alphaville** [comment]
Folks, do we still need this issue?

**Comment by jamie-54** [comment]
No closing now
