### ISSUE TITLE
Guide to setup R-Pi environment

### ISSUE THREAD

**Issue by patchedByBatman** [QUB-ASL/bzzz#70]
Step-by-step installation guide

## OS installation (Section Incomplete)
1. Use Bullseye.
2. Install VS code.
3. Install Anydesk.

## VS code setup (Section Incomplete)
1. Install git and git tools.
2. Install remote explorer.
3. Setup git.

**After completing writing this, update `README.md` accordingly.**

**Comment by alphaville** [comment]
We need a complete installation giude including how to install all necessary dependencies (e.g., `pigpio`, virtual environment, etc).

**Comment by alphaville** [comment]
@gunturiCM has this issue been resolved?

**Comment by gunturiCM** [comment]
> @gunturiCM has this issue been resolved?
Not yet professor. I will write the full details after I am done with my report.

**Comment by alphaville** [comment]
@jamie-54 we can close this, right?
