### ISSUE TITLE
Sensor board design for BNO055

### ISSUE THREAD

**Issue by boyle26** [QUB-ASL/bzzz#89]
New board sensor board design replacing the older VL53L0X IMU with the Bosch BNO055. This will include
-Schematics
-Board layouts
-Gerber files

Waiting on test results to determine which IMU to move ahead with design. No point seen in designing two boards with if only one will be used.

**Comment by alphaville** [comment]
@jamie-54 shall we close this?

**Comment by jamie-54** [comment]
yea
